### ISSUE TITLE
Is Zeehaven working

### ISSUE THREAD

**Issue by SMRFoundation** [PublicDataLab/zeehaven#5]
I am no longer getting a csv after dropping an ndjson file.
Is there  work around?

Thank you!

**Comment by iaine** [comment]
What service (Twitter, TikTok et al.) are you trying to convert? I've just used Twitter and it is responding correctly.

**Comment by SMRFoundation** [comment]
Instagram.Thank you!MarcSent from my iPhoneOn Oct 30, 2024, at 4:56 AM, Iain Emsley ***@***.***> wrote:﻿
What service (Twitter, TikTok et al.) are you trying to convert? I've just used Twitter and it is responding correctly.

**Comment by SMRFoundation** [comment]
My mistake, the file is from TikTok.

**Comment by iaine** [comment]
Ah, no worries, got it thanks. Will come back as soon as I can.

**Comment by iaine** [comment]
I've found the bug in parsing urls and escaping stickers and fixed both. I have tested Zeehaven with your data and have a CSV. If you can confirm this is working for you, I'll close the ticket.

**Comment by SMRFoundation** [comment]
Yes, it is working.

Thank you for the quick engagement and resolution!

Regards,

Marc

**Comment by iaine** [comment]
Ah, no worries. Glad it's fixed. :)

**Comment by iaine** [comment]
I've fixed that bug. 

If you open up the web developer tools, the site prints any errors there. However, I'll have a think about other options for a future release. 

Apologies for the frustration. Best, Iain

**Comment by iaine** [comment]
Should be handled now.

**Comment by SMRFoundation** [comment]
Still getting that error.
![image](https://github.com/user-attachments/assets/7b40927a-866e-407a-93b6-cb60258576a0)

**Comment by iaine** [comment]
Have you refreshed the page? It might take a minute for Github to serve the update.

**Comment by SMRFoundation** [comment]
Tried different machine and a different browser:

[image: image.png]

**Comment by SMRFoundation** [comment]
Zeehaven looks like it is back in full function.
Thank you!

**Comment by iaine** [comment]
Great thanks for confirming.

**Comment by SMRFoundation** [comment]
Thank you!
